### ISSUE TITLE
Local-Job-Gen.ps1 cannot compile coreclr/netci.groovy

### ISSUE THREAD

**Issue by sejongoh** [dotnet/dotnet-ci#209]
Local-Job-Gen.ps1 cannot compile coreclr/netcli.groovy with the following error.

```
[JarClassLoader] INFO:  findResource(): unable to locate "jobs/generation/UtilitiesCustomizer.groovy"                                 
[JarClassLoader] INFO:  findResource(): unable to locate "jobs/generation/UtilitiesCustomizer.groovy"                                 
Exception in thread "main" java.lang.reflect.InvocationTargetException                                                                
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)                                                                
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)                                                            
        at java.lang.reflect.Method.invoke(Unknown Source)                                                                            
        at com.simontuffs.onejar.Boot.run(Boot.java:313)                                                                              
        at com.simontuffs.onejar.Boot.main(Boot.java:161)                                                                             
Caused by: javaposse.jobdsl.dsl.DslScriptException: (combinednetci.groovy, line 421) No signature of method: javaposse.jobdsl.dsl.help
rs.triggers.TriggerContext.githubPullRequest() is applicable for argument types: (jobs.generation.Utilities$_addGithubPRTriggerImpl_cl
sure8_closure29_closure30) values: [jobs.generation.Utilities$_addGithubPRTriggerImpl_closure8_closure29_closure30@402e37bc]          
        at javaposse.jobdsl.dsl.DslScriptLoader.runDslEngineForParent(DslScriptLoader.java:79)                                        
        at javaposse.jobdsl.dsl.DslScriptLoader.runDslEngine(DslScriptLoader.java:135)                                                
        at javaposse.jobdsl.dsl.DslScriptLoader$runDslEngine.call(Unknown Source)                                                     
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)                                      
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)                                      
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)                                      
        at javaposse.jobdsl.Run$_main_closure2.doCall(Run.groovy:36)                                                                  
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                
```

```
def private static addGithubPRTriggerImpl(def job, String branchName, String contextString, 
String triggerPhraseString, boolean triggerOnPhraseOnly, boolean permitAllSubmittters, Iterable<String> permittedOrgs, Iterable<String> permittedUsers) {
        job.with {
            triggers {
                githubPullRequest {  <- line 421
                    useGitHubHooks()
                    if (permitAllSubmittters) {
                        admin('Microsoft')
                    }
                    admin('mmitche')
                    if (permitAllSubmittters) {
```

**Comment by sejongoh** [comment]
It would be great if this script can be fixed soon since this script is very useful and we are updating coreclr groovy file to enable GC stress testing.

**Comment by mmitche** [comment]
@sejongoh I'll try my best, but you shouldn't block on this.

**Comment by sejongoh** [comment]
@mmitche Thanks! Just to confirm, is there any better way than "@dotnet-bot test ci" to check the script changes?

**Comment by mmitche** [comment]
You can probably work around this in the meantime by:

1) Cloning dotnet-ci and changing "githubPullRequest" in the Utilities class to "pullRequest"
2) Local-Job-Gen can take the parameter of the location of the Utilities file.  Specify the local copy.

**Comment by sejongoh** [comment]
Thanks! It works well.
