### ISSUE TITLE
PlatformException gets thrown when trying to run dotnet-cli

### ISSUE THREAD

**Issue by wmeints** [dotnet/dotnet-ci#231]
I just installed the latest beta (1.0.0-beta-001598) on my Mac running OS X 10.11.3.
When I try to run the dotnet utility using the following command:

```
dotnet --version
```

I run into the following nasty error. 
It seems as if it cannot find libc somehow. 

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception. ---> System.PlatformNotSupportedException: Error reading Darwin Kernel Version ---> System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Extensions.PlatformAbstractions.Native.NativeMethods.Darwin.sysctl(Int32* name, UInt32 namelen, Byte* oldp, UInt32* oldlenp, IntPtr newp, UInt32 newlen)
   at Microsoft.Extensions.PlatformAbstractions.Native.NativeMethods.Darwin.GetKernelRelease()
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.PlatformAbstractions.Native.NativeMethods.Darwin.GetKernelRelease()
   at Microsoft.Extensions.PlatformAbstractions.Native.PlatformApis.GetDarwinVersion()
   at Microsoft.Extensions.PlatformAbstractions.Native.PlatformApis.GetOSVersion()
   at Microsoft.Extensions.PlatformAbstractions.DefaultRuntimeEnvironment..ctor()
   at Microsoft.Extensions.PlatformAbstractions.DefaultPlatformServices..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Cli.Program.PrintVersionInfo()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by mmitche** [comment]
@wmeints Can you file this in the dotnet/cli repo issues?  That's probalby the best place for it.
